import Pizza from '../images/piza.jpg';

export const pizzaList =[
    {
        id: 1,
        name: "Pizza 1",
        price: 100,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 1 Description",
        pizzaType: "Veg",
    },
    {
        id: 2,
        name: "Pizza 2",
        price: 200,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 2 Description",
        pizzaType: "Non-Veg",
    },
    {
        id: 3,
        name: "Pizza 3",
        price: 300,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 3 Description",
        pizzaType: "Veg",
    },
    {
        id: 4,
        name: "Pizza 4",
        price: 400,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 4 Description",
        pizzaType: "Veg",
    },
    {
        id: 5,
        name: "Pizza 5",
        price: 500,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 5 Description",
        pizzaType: "Non-Veg",
    },
    {
        id: 6,
        name: "Pizza 6",
        price: 600,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 6 Description",
        pizzaType: "Veg",
    },
    {
        id: 7,
        name: "Pizza 7",
        price: 700,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 7 Description",
        pizzaType: "Non-Veg",
    },
    {
        id: 8,
        name: "Pizza 8",
        price: 800,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 8 Description",
        pizzaType: "Veg",
    },
    {
        id: 9,
        name: "Pizza 9",
        price: 900,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 9 Description",
        pizzaType: "Veg",
    },
    {
        id: 10,
        name: "Pizza 10",
        price: 1000,
        image: Pizza,
        base: "Thick",
        size:"Medium",
        stage: "Order Placed",
        description: "Pizza 10 Description",
        pizzaType: "Veg",
    },
]